# Generated by Django 4.2.7 on 2025-12-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_locations', to='departments.department')),
            ],
            options={
                'verbose_name': 'Рабочая локация',
                'verbose_name_plural': 'Рабочие локации',
                'db_table': 'work_locations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='work_locati_latitud_3fbb9d_idx')],
            },
        ),
    ]
