# Generated by Django 4.2.7 on 2026-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklocation',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='address_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='address_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
