# Generated by Django 4.2.7 on 2026-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_worklocation_address_en_worklocation_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklocation',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='worklocation',
            name='name_en',
        ),
    ]
