# Generated by Django 4.2.7 on 2025-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checkout_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checkin_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('checkin_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('checkout_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('checkout_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.IntegerField(default=0)),
                ('face_verified', models.BooleanField(default=False)),
                ('location_verified', models.BooleanField(default=False)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учет рабочего времени',
                'verbose_name_plural': 'Учет рабочего времени',
                'db_table': 'attendance',
                'ordering': ['-checkin_time'],
            },
        ),
    ]
