# Generated by Django 4.2.7 on 2026-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название компании'),
        ),
    ]
