# Generated by Django 4.2.7 on 2026-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_name_en_company_name_ru_company_name_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name_en',
        ),
    ]
