# Generated by Django 4.2.7 on 2026-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=500)),
                ('encoding', models.JSONField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото для Face ID',
                'verbose_name_plural': 'Фото для Face ID',
                'db_table': 'face_photos',
            },
        ),
    ]
