# Generated by Django 4.2.7 on 2025-12-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('face_id', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facephoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='facephoto',
            index=models.Index(fields=['user'], name='face_photos_user_id_51407b_idx'),
        ),
    ]
