# Generated by Django 4.2.7 on 2026-01-03 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'status'], name='requests_user_id_2e1dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['start_date', 'end_date'], name='requests_start_d_b41acd_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['user', 'period'], name='penalties_user_id_2f4a69_idx'),
        ),
    ]
