# Generated by Django 4.2.7 on 2025-12-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['user', 'period'], name='salaries_user_id_eec01d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('user', 'period')},
        ),
    ]
