# Generated by Django 4.2.7 on 2026-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_time', models.TimeField(verbose_name='Время начала работы')),
                ('end_time', models.TimeField(verbose_name='Время окончания работы')),
                ('break_duration', models.IntegerField(default=60, verbose_name='Длительность перерыва (минуты)')),
                ('work_days', models.JSONField(default=list, verbose_name='Рабочие дни')),
                ('late_threshold', models.IntegerField(default=15, verbose_name='Порог опоздания (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'db_table': 'work_schedules',
                'ordering': ['name'],
            },
        ),
    ]
