# Generated by Django 4.2.7 on 2026-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_description_en_department_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='name_en',
        ),
    ]
